---
# Configure vmtools

- name: service is enabled and started
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  become: true
  loop: "{{ vmtools_services_enable }}"
  when: vmtools_enable_service
